### PR TITLE
Move some structs from space-internal.h to space.h so propagation1d.c can stop including laik-internal.h

### PR DESCRIPTION
**Pull request by AlexanderKurtz**

### CODE REVIEW

**Comment by weidendo** [comment]
I really want these structs to stay internal.

If propagation1d needs to access them, there should be getters/setters. If not existing yet, we need to add them.

**Comment by AlexanderKurtz** [comment]
Yeah, I figured that these structs ought to be internal, but unfortunately the ```propagation1d``` example currently accesses them directly which clearly breaks the definition of "internal". However, I think this PR can still be useful as sort of bug report against ```propagation1d```:

@amir-raoofy since you apparently wrote ```propagation1d``` (according to git blame), could you talk to @weidendo to figure out which part of the structs touched in in this PR should have getters/setters and then maybe add those?

The background is that I'm trying to move the "internal" headers from ```include``` to ```src``` so that 
```include``` == API and ```src``` == Implementation holds true. I think this is a good idea because we are then actually forced to use the public API in our examples and no longer have the option of simply "peeking" into internal data structures.

**Comment by weidendo** [comment]
The intention is good, but keep two things in mind:
* a lot of files from examples/ currently are not really examples for end users, demonstrating the API. They started like that, but changed to become test cases, with a lot of things which just confuse as examples. Ie. they should be copied into tests/ and cleaned up as examples.
* there are two levels of LAIK header use: one for the LAIK end user, and one for LAIK plugin developers. The "internal" headers in include/ are actually meant to be for plugin development, and even with a compiled LAIK installation, plugin development should be possible and needs to be installed.

**Comment by AlexanderKurtz** [comment]
Ok, so this seems to be a bigger issue then and will probably take some time to tackle. Could we maybe start by discussing the follow rules (keywords as defined in [RFC 2119](https://www.ietf.org/rfc/rfc2119.txt))?

 1. Paths below ```include``` MUST begin with ```laik```.
 2. When building LAIK (as in the project), both ```include``` and ```src``` MUST be in the include path.
 3. The examples SHOULD only include headers from ```include```.
 4. ```#include "foo.h"``` MUST NOT be used if ```foo.h``` is not in the same directory.

Are these OK?

**Comment by weidendo** [comment]
> 1. Paths ...

Yes. I am also fine if a header name shows up as "/usr/include/laik/bla.h" - is that included in your rule?

> 2. / 4.

Sounds good.

> 3.

It has to be MUST. Everything else will confuse LAIK users.
IMHO examples should be small and easy to understand by just looking at one file.

**Comment by AlexanderKurtz** [comment]
Ok, with your comments incorporated, how about merging this into ```docs/includes.md```?

--- SNIP ---

Header files in LAIK are subject to the following rules; the keywords are to be interpreted according to [RFC 2119](https://www.ietf.org/rfc/rfc2119.txt):

1. Files and directories below ```include``` MUST begin with ```laik```.
2. When building LAIK (as in the project), both ```include``` and ```src``` MUST be in the include path.
3. The examples MUST only include headers from ```include```.
4. ```include "foo.h"``` MUST NOT be used if ```foo.h``` is not in the same directory.

**Comment by weidendo** [comment]
Fine, but better into a fitting subsection of "Guidelines.md"?

**Comment by amir-raoofy** [comment]
Hi Alexander,

Sorry for my late response, I was on vacation. Thanks for the changes!

**Pull request closed without merging**
