### PR TITLE
Add meson as an alternative build system.

### PR DESCRIPTION
**Pull request by AlexanderKurtz**

### CODE REVIEW

**Comment by twittidai** [comment]
I would suggest to put this on hold until redesign (scheduled for Mid Jan.)

**Comment by AlexanderKurtz** [comment]
Well, but it *is* really useful, all of my pull requests from today basically just fall out of having a proper build system...

**Comment by weidendo** [comment]
Curious: what are you missing in the Makefile's which is provided by Meson out-of-the-box? Is this about enabling warnings?

**Comment by AlexanderKurtz** [comment]
Oh, a hell of a lot:

 1. Proper build directory support. Building in the source directory is just ... ewww.
 2. Proper filename support. Just saying "well, don't put special characters in filenames then" isn't an answer.
 3. Support for building the project with different options at the same time.
 4. An actual list and interface for getting and setting build options.
 5. Proper support for dependency tracking without me having to worry about compiler flags.
 6. Actually, I don't want to have to care about compiler flags at all. There's a gazillion compiler (versions) out there, and they all have horrible command line interfaces.
 7. A syntax telling the machine *what* I want, not *how* I want it done.
 8. The ability to tolerate indention by spaces without crashing.
 9. No shell invocations. This is all fun and games until you miss the little space in ```rm -rf * .o```
 10. While we are at it, actual ```clean``` support. I don't want do guess if my commit might contain build results or not (#36), I want to know it doesn't.

Last but not least: I didn't know anything about meson before last week. Writing the initial Implementation took an afternoon (because there actually is *useful* documentation available). Getting the Makefile-based system on-par w.r.t. the points above has been going for the last couple of days.

**Comment by twittidai** [comment]
There is a fatal reason why I cannot integrate meson for this (our any other build system). It is not clear if on a HPC system this build system is available. I have check on the Linux Cluster, there is only cmake2.8/3.4/3.6 available, but cmake there cannot find all packages on the Linux Cluster due to the module system. 
The only reliable solution on that cluster is Makefile. Since this is the target of LAIK, I cannot convince myself to change the build system.

**Comment by AlexanderKurtz** [comment]
This PR (no longer) proposes to *switch* the build system, instead it adds an alternative. The purpose is mainly to make [the life of developers easier](https://github.com/envelope-project/laik/pull/15#issuecomment-347374049). If we ever decide to actually *switch*, prior testing on all target platform is obviously required. And again, this can all be reverted with ```find -name 'meson*' -delete```, so please reconsider!

**Comment by AlexanderKurtz** [comment]
Just out of my personal curiosity:

 1. What kinds of HPC systems are we talking about?
 2. What distributions are running there?
 3. Which parts of LAIK actually need to build there? Just liblaik.so, or also the examples, etc.?
 4. Why can't we ship a pre-built .deb/.rpm or .tar.gz?
 5. Why can't we just build the entire application using liblaik statically on a development machine?

**Comment by twittidai** [comment]
Hi
1. Typical Clusters , such as the LRZ Linux Cluster/MACCluster
2. SLES
3. Only liblaik.so (for experiments also other stuff)
4. You cannot install stuff there using .deb/.rpm, but you can supply a liblaik.so and headers. 
5. Then you need a cross compiler to enable features like AVX512, which is quite expansive....

**Comment by AlexanderKurtz** [comment]
I don't think you need a cross compiler as long as the base architecture is the same (i.e. x86_64). My machine doesn't have AVX512, but I can compile programs with it enabled just fine, while running them obviously doesn't work:

```
alexander@shepard:~$ cat main.c 
#include <stdio.h>
#include <immintrin.h>

int main (int argc, char** argv) {
    __m512i a;
    __m512i b;
    a = b;
    printf ("Hello World\n");
}
alexander@shepard:~$ gcc -mavx512f main.c 
alexander@shepard:~$ ./a.out 
Illegal instruction
alexander@shepard:~$ 
```

But in general I get your point: People don't want to explicitly figure out the required compiler flags for optimal performance, they just want to use ```-march=native``` and be done with it. And that means compiling has to happen on the target machine. Does that sum things up correctly?

**Comment by twittidai** [comment]
yes. you get the point.
Typically in HPC environment one does compiling on the target machine..

**Comment by AlexanderKurtz** [comment]
Ok, and since the code in liblaik.so may contribute significantly to the overall performance of the main application, this also applies there and we **cannot** just ship a pre-built shared object + headers, right?

**Comment by twittidai** [comment]
I would like to hear the answer from @weidendo

**Comment by weidendo** [comment]
Ok, this actually forced us to discuss this now internally, but that is very good!

We want to use the same build system for all our projects. And this now very probably will become CMake, as this has very good backing in the HPC community. I'll keep you updated.

**Comment by AlexanderKurtz** [comment]
Sure, using CMake would be fine too. But meson support is here right now, and if we ever get around to actually switching to CMake, it can trivially be removed again!

**Comment by twittidai** [comment]
I prefer not to merge work in progress solution into master.
We will reconsider this at the end of this week.

**Comment by AlexanderKurtz** [comment]
Sure, there's no hurry here!

**Comment by AlexanderKurtz** [comment]
This PR is obviously not going to get merged in it's current form, so I'm closing it for now. I will however be keeping maintaining a [*meson* branch in my personal repository here](https://github.com/AlexanderKurtz/laik/tree/meson), so I can always create a new PR if requested!

**Pull request closed without merging**
