### PR TITLE
examples/propagation2d.c: Fix unused variables and parameters warnings.

### PR DESCRIPTION
**Pull request by AlexanderKurtz**

### CODE REVIEW

**Comment by twittidai** [comment]
Propagation 2d is an active working in progress code and should not be engineered at this moment.

**Comment by AlexanderKurtz** [comment]
Then why is this code in master if it is WIP? Shouldn't this be developed in a separate repository/branch and only be merged in a PR when it's ready? I'd really like to get to ```-Werror``` on master soon and #33 and this are the only blockers left.

**Comment by weidendo** [comment]
Does Github support push hooks which can refuse a push to succeed?
Then the hook can check our guidelines and refuse to accept the push. Would be nice to know.

**Comment by AlexanderKurtz** [comment]
Commit 886c48f3b89c85c5662ea7fcfeccba242a7fc693 included the changes suggested here, so I'm closing this PR!

**Pull request closed without merging**
