### PR TITLE
[RFC] Switch the build system to meson.

### PR DESCRIPTION
**Pull request by AlexanderKurtz**
LAIK currently uses a custom-built build system which isn't very flexible or user-friendly. If we want to get LAIK into distros eventually, having a proper and well-known build system will make this a lot easier. But meson also provides us with a couple of clear advantages today:

 * Smaller footprint (have a look at the diffstat)
 * Better readable code
 * No fragile shell magic
 * Properly supports compile-time options, new options can be added easily
 * ...

You'll need a relatively recent ```meson``` for this work, however both Debian¹ and Ubuntu² provide reasonably up-to-date backports for their stable releases. Please have a look and tell me what you think!

[1] <https://packages.debian.org/stretch-backports/meson>
[2] <https://packages.ubuntu.com/xenial-backports/meson>

### CODE REVIEW

**Comment by weidendo** [comment]
Hi Alexander,

thanks for the effort to show what is needed to switch to meson!
Everybody has his/her own favorite build system, and I actually
would prefer CMake if we go that path.

However, at this point it is just easier to stay with what we have.
We want this to compile out-of-the-box on standard HPC system
environments, which easily may be 5-6 years old (eg. SLES11).
Even python v3 is bad in this regard: e.g. it must be installed in
the default up-to-date Travis base image, which is based on
Ubuntu "trusty" (!).

**Comment by AlexanderKurtz** [comment]
Hi!

Sorry about forgetting about Travis, I completely missed that. While I think that Travis can be convinced to work with meson somehow¹, I do get the point regarding the often ancient OS versions on HPC systems (I fought with one during my Bachelor thesis and remember hating it with a passion). However, I'd still like to get at least optional support for building with meson, since this is in invaluable development tool: Builds are faster, it's a lot harder to make mistakes and the support for a wide variety of build options (e.g. debug, optimized, etc.) avoids having to memorize the (often arcane) compiler command line options.

So, would you be willing to accept a patch adding a bunch of ```meson.build``` files (and changing nothing else)? The old build system would still be there, the ```README.md``` would still point to it, and removing meson support again would be as simple as ```find -name 'meson*' -delete```. The idea would basically be, to try this out and evaluate whether switching to meson is worth it over the next few months!

[1] http://mesonbuild.com/Continuous-Integration.html#continuous-integration

**Comment by weidendo** [comment]
I already have a few files in ".qtcreator/" which only I am using, to make my IDE happy.
So if this is not too distracting, I would be fine with it...

I suppose it is not possible to keep the meson files in a subdirectory ".meson" instead of
spreading them all over all directories? Now I am wondering if git could support overlay checkouts,
ie. multiple repositories checked out into the same directory hierarchy :-)

BTW, build speed currently is not an issue.
> time (make clean; make -j8)
...
real	0m1,318s
user	0m3,648s
sys	0m0,486s

For testing with an optimized build, I currently do "make clean; make OPT=-O2"

**Comment by AlexanderKurtz** [comment]
Great, I just opened #15!

**Pull request closed without merging**
