### PR TITLE
Makefile: Enable additional warnings, but don't yet make warnings fatal.

### PR DESCRIPTION
**Pull request by AlexanderKurtz**
Since we want this not only for liblaik itself, but also for all other parts
of LAIK, this commit also changes the build system to so that every Makefile
includes the top-level Makefile.common file (which includes the
Makefile.config file). This has the nice side effect of making the other
Makefiles more readable and also streamlines the compiler options across the
project (as far as possible).

### CODE REVIEW

**Comment by twittidai** [comment]
Thanks for being so productive. 
However, I would not suggest to merge this at this point (but sure for the time after redesign), since we are still in dirty-coding mode for the main LULESH port.

**Comment by AlexanderKurtz** [comment]
The warnings are not yet fatal, so "dirty-coding" would still work. However, I have often experienced that making warnings fatal pointed me to my mistakes early on, which actually made development both easier and faster.

**Comment by AlexanderKurtz** [comment]
Ok, I just force-pushed an overhauled version of this: Building in subdirectories works and so does ```make WARNINGS=``` to disable all warnings. Travis likes it too. Anything else?

**Comment by weidendo** [comment]
IMHO this PR now does too much in one patch...
The double-indirection (including Makefile.config in Makefile.common) makes it tricky to understand the logic, easily resulting in bugs to be introduced. "make install PREFIX=$HOME" does not work any longer, as well as "make OPT=-O2"...

Let's keep it open for now as reminder that we wanted to add more warning ouputs...

**Comment by AlexanderKurtz** [comment]
* ```make install PREFIX=foo``` works for me, what exactly is the problem here?
* I can change ```Makefile.common``` to include $(OPTS). Do you want it to affect only CFLAGS or also CXXFLAGS and LDFLAGS?
* If you want, I can change it so that every Makefile includes both ```Makefile.config``` and ```Makefile.common``` (in that order), but since ```Makefile.common``` needs variables from ```Makefile.config```, this is IMHO harder to understand and more fragile than the current approach
* Regarding overall complexity: I do agree, this all isn't very nice, but I want consistent compiler options across the project and you want subdir-make compatibility, so I don't see any other way to do this here.

**Comment by AlexanderKurtz** [comment]
Ok, so I just pushed a new version, in which ```Makefile.common``` now prepend its options to ```CFLAGS``` etc., so ```Makefile.config``` or environment variables (a.k.a. humans) can override earlier options. IMHO everything works now:

- Subdir make-ing: ```cd external/FT-STIM/ && make```
- Prefix installation: ```mkdir -p foo/include && PREFIX=foo make install```
- Prefix uninstallation: ```mkdir -p foo/include && PREFIX=foo make uninstall```
- Disabling all warnings: ```WARNINGS= make```
- Overriding CFLAGS etc.: ```CFLAGS=-O1 CXXFLAGS=-O2 LDFLAGS=-M make```

Any thoughts?

**Comment by AlexanderKurtz** [comment]
Commit a52ad26a04ff161252d5094d202abf18b04a4b69 introduced something similar and this PR has merge conflicts now, so let's close this for now.

**Pull request closed without merging**
