### PR TITLE
external/FT-STIM: Remove all build results from the repository.

### PR DESCRIPTION
**Pull request by AlexanderKurtz**

### CODE REVIEW

**Comment by twittidai** [comment]
The Fault Simulator is currently not in scope.

**Comment by AlexanderKurtz** [comment]
Hmm? What does this have to do with removing (binary) build results from the git repository?

**Comment by twittidai** [comment]
I'm just thinking to remove the FT-SIM folder completely

**Comment by AlexanderKurtz** [comment]
Sure, that'll work as well. But this doesn't conflict with this PR, so you could still merge this and then delete the directory when ready.

**Comment by twittidai** [comment]
sure.

**Pull request merged**
