### PR TITLE
examples/vsum2.c: Remove unused but set variables.

### PR DESCRIPTION
**Pull request by AlexanderKurtz**

### CODE REVIEW

**Comment by weidendo** [comment]
Do we really need the "(void)" stuff? Is this about explicitly ignoring return values to kill some warning?

**Comment by AlexanderKurtz** [comment]
Two reasons:

 1. Tell humans reading this code that ignoring the return value was intentional.
 2. GCC supports marking functions with a ```__attribute__((warn_unused_result))``` [1], and will then warn if such a function result is ignored. We may eventually want to use this attribute on some functions.

[1] https://gcc.gnu.org/onlinedocs/gcc-3.4.3/gcc/Function-Attributes.html

**Comment by weidendo** [comment]
Telling humans that ignoring the return value is intentional only makes sense if the return value usually should not be ignored in the first place, ie. if we use the attribute you cite.

But in both cases, the return value only provides additional information.
For laik_switchto_new(), we give back the created new partitioning, which may be used later in the application again. And for laik_mapXXX, the returned Mapping can be used to get more information about the mapping of the data.

**Comment by AlexanderKurtz** [comment]
Well, if you want the ```(void)``` cast removed, sure I can do that. But I personally just don't like silently dropping return values, especially in code I didn't originally write! ;-)

**Comment by AlexanderKurtz** [comment]
I just force-pushed a new version without the ```(void)``` casts, please review!

**Comment by twittidai** [comment]
This can be merged from my point of view.

**Comment by twittidai** [comment]
From my view this can be merged.

**Pull request merged**
