### PR TITLE
Dockerfile: Switch to CMake.

### PR DESCRIPTION
**Pull request by AlexanderKurtz**
This depends on #107.

### CODE REVIEW

**Comment by weidendo** [comment]
I do not think we should switch to cmake in Travis, yet.

**Comment by AlexanderKurtz** [comment]
> I do not think we should switch to cmake in Travis, yet.

Why? Is there something I can improve to make this work?

**Comment by twittidai** [comment]
This is because all parallel development relays on the makefile.
Therefore, this will not be done until somewhere in the future...

**Comment by weidendo** [comment]
Why do you care? From the build system point of few, every test currently is triggering a command.
This is easy. But I have no idea if this is enough.

We really should have other test types in place, which may need their own test drivers or own post-processing, which cmake can not handle.

I can imagine that a part of the test suite must integrate with SLURM to submit jobs and collect
results afterwards, e.g. for large scale tests.  This is something Travis is useless anyway...

**Comment by AlexanderKurtz** [comment]
Just for the record:

 1. This PR doesn't remove the Makefiles, building and testing LAIK with ```make``` still works, just like before.
 2. I don't see how a specific test should be impossible with CMake, its test interface is about as generic as possible.
 3. Switching Travis to CMake has clear advantages: We actually build all of LAIK, use a consistent (and more strict) set of compiler flags, and will fail hard if the forget to add a dependency to the Dockerfile.

**Comment by weidendo** [comment]
It's easy: if I add my next test to the Makefile, Travis won't run my test if we go to cmake.
You can switch on cmake in your fork, if you want.

**Comment by AlexanderKurtz** [comment]
Adding a test to CMake would literally be a one-line change (e.g. [here](https://github.com/envelope-project/laik/blob/master/tests/mpi/CMakeLists.txt)). That doesn't seem to be an unreasonable effort for a transition period. Well, unless there won't be a transition and LAIK will stay with its current Makefile system. If that's the case, please tell me so.

**Comment by weidendo** [comment]
> one-liner

I know.

> will stay ... Makefile

Not with tests in just a Makefile. Perhaps a python script instead.
I do not know. That's the whole point of the exercise.

**Comment by AlexanderKurtz** [comment]
Unfortunately that doesn't really answer my question. Will LAIK switch to a proper build system (i.e. meson, CMake, or similar) or will it stay with the current Makefile-system?

**Comment by twittidai** [comment]
He answered you. It will obviously stay with makefile :0

**Comment by AlexanderKurtz** [comment]
Ok, I can work with that, I just wanted a clear statement here!

**Comment by weidendo** [comment]
> Will LAIK switch to a proper build system ...

Makefiles are a proper build system, as long as its simplicity is enough for a project :-)
And of course it has its well-known limits.

That said, it is nice to see the equivalent cmake syntax, but we will not switch now.

**Comment by AlexanderKurtz** [comment]
I just thought about this some more and think I have an idea: Since the CMake build happens in a subdirectory anyway, would it be acceptable if we built with CMake in addition to the current make build? I.e. something like this:

```Dockerfile
# Build and test with make
RUN CC="${CC}" CXX="${CXX}" ./configure
RUN OMPI_CC="${CC}" make
RUN make test

# Build and test with CMake
RUN mkdir "build"
WORKDIR "build"
RUN CC="${CC}" CXX="${CXX}" cmake -D "CMAKE_EXPORT_COMPILE_COMMANDS=1" -D "documentation=off" -D "skip-missing=off" ".."
RUN make
RUN ctest
RUN find '../src' -name '*.c' -print0 | xargs --null --max-args='1' clang-tidy -p 'compile_commands.json'
```

Since the actual build doesn't take very long (Travis spends the overwhelming amount of its time downloading packages), this shouldn't delay the CI runs noticeably, and it would give us the biggest possible build and test coverage!

**Comment by weidendo** [comment]
What do you want to achieve?
If this 2nd test run is expected to check if the cmake tests are in sync with the makefile
tests, this does not work. We would need to collect the sequence of tests done, and check
if they are the same. I think this is complete overkill.

What we can do: Mark a commit subject with [Test added] if it adds a test, similar the
marking API changes.

**Comment by AlexanderKurtz** [comment]
> What do you want to achieve?

I want to merge the TCP backend and have its tests run in every Travis run from now on. Without CMake, I would have to:

 * Write a Makefile for the TCP backend (non-trivial since it should be an optional part of LAIK in a subdirectory and needs quite a few CFLAGS/LDFLAGS).
 * Extend ```configure``` to check for my dependencies and enable/disable the TCP backend accordingly. Also non-trivial and the script is too hard to read already.
 * Extend the test logic to run my tests, but only if the TCP backend was built.

I don't want to do any of that by hand. I want to use a configuration/build system designed for these things.

**Comment by twittidai** [comment]
Is it possible to do the RUN commands in Makefile only for you backend while leaving Makefile for Josef in place?

**Comment by AlexanderKurtz** [comment]
@twittidai: Not sure if I understand you correctly. Do you mean something like I suggested in https://github.com/envelope-project/laik/pull/108#issuecomment-374070909 ?

**Comment by twittidai** [comment]
@AlexanderKurtz more or less - just with CMake covering only your part. 
But your suggestion ist also good, since it's the superset. @weidendo I'm with Alexander this time.

**Comment by weidendo** [comment]
Can we just merge it?
Shouldn't it work similar to current MPI backend, ie. compiled only if "USE_TCP" is defined?
And I suppose the tests are in a "tcp/" subdirectory?

**Comment by twittidai** [comment]
But then travis is testing not all stuff.

**Comment by weidendo** [comment]
Step by step?

**Comment by weidendo** [comment]
The merge procedure should not matter much - we want to have the test suites in sync anyway as soon as possible.

**Comment by twittidai** [comment]
ok. @AlexanderKurtz forget the tests then.

**Comment by AlexanderKurtz** [comment]
To make sure we are all talking about the same thing and have some actual code to look at, I just filed #116, so let's decide there whether we want to build with CMake in addition to Make!

**Pull request closed without merging**
