### PR TITLE
Added compiler switch and basics for tracking number of MPI Messages …

### PR DESCRIPTION
**Pull request by twittidai**
Added compiler switch and basics for tracking number of MPI Message and time.
To test: Enable LAIK_MPI_PROFILING while building. A statistics ist given at the end of each programm exection.

### CODE REVIEW

**Comment by weidendo** [comment]
For statistics, Laik_SwitchStat is already in place, and results are printed out at the end with
LAIK_LOG=2. Everything your MPIProfData is collecting is already covered.

For time measurements of every single MPI call, it is much better to use mpiP (external tool).
This easily can be supported also by the miniMPI in the TCP backend.

Otherwise, we want the times spent in the backend API functions, which can be outside
of backend code. Which we already do (partially?).

We should have an external API in place to provide the data to the visulization (not printf).

**Review by weidendo — CHANGES_REQUESTED** [review]
Why isn't there a way to select "NAK"?

**Comment by twittidai** [comment]
if you like it to be so

**Comment by twittidai** [comment]
But I don't know if its good to mix up switch and backed operations, as you have done in your implementation, it is obvious that some switches generate no action and some generates a huge a mount of operations. E.g. in your lulesh baby I tracked 3993 send calls, and 305 all reduces and you only have 202 switches. but if you say this should be measured by mpip then thats ok. 

> Otherwise, we want the times spent in the backend API functions, which can be outside
> of backend code. Which we already do (partially?).

Yes and no, you can't know how long your backend code is running and how long mpi is running. I don't see another way to do this except ask com-lib for time. Probably you have better way, you are expert.

**Comment by weidendo** [comment]
> But I don't know if its good to mix up switch and backed operations...

Not sure I understand this. Where are we mixing something up? Do you mean the "LAIK_LOG=2"-output at the end? Of course we can add further summary lines here.

Regarding pure MPI time... using mpip really seems the best solution here. The wrapping of MPI calls via LD_PRELOAD does exactly the same as your ifdefs did in the PR. Or do I miss something here?

>> Otherwise, we want the times spent in the backend API functions, which can be outside of backend code. Which we already do (partially?).

> Yes and no, you can't know how long your backend code is running and how long mpi is running.

Why not just compare backend time measurements from LAIK with output from mpip?

**Comment by twittidai** [comment]
> Not sure I understand this. Where are we mixing something up? Do you mean the "LAIK_LOG=2"-output at the end? Of course we can add further summary lines here.

Your output Switch-Statistics give out the number of switches, not the number of actual operations executed by the backend. You don't even count the number of MPI operations acutally carried out yet (so far I saw in the mpi-backend.c". Ok, I admit, if we are using MPI (and other stuff), then another tool can do this, that is correct. 
So you think it is best if these kind of profiling information is the responsibility of communication lib?

**Comment by weidendo** [comment]
Hm. Every single activity done by the communication backend maps to a single action (even if
it is not recorded as such, but directly executed). Some will be generic, some backend-specific.
But every action maps to an action type (some int), and a backend could also give each action
a name at initialization. This way, we still can collect every backend-specific action, and even could
do histograms on the parameters of actions (e.g. message size).

The nice thing with action sequences is that the list of actions will be known, and thus, collection
is not really an overhead: it often should be enough to count the number of executions of sequences,
and do the summary afterwards.

**Pull request closed without merging**
