### PR TITLE
Mark laik_log() as a printf-style function and fix the corresponding bugs.

### PR DESCRIPTION
**Pull request by AlexanderKurtz**

### CODE REVIEW

**Comment by weidendo** [comment]
Thanks!
Only one thing: using %j and max_t types seems quite uncommon to me (I had to look it up), and I see no point not to just use a 64bit type (e.g. %llu and uint64).

**Comment by AlexanderKurtz** [comment]
> Only one thing: using %j and max_t types seems quite uncommon to me (I had to look it up), 

Yeah, I had to look this up too. The problem is that there is apparently no correct printf specifier for fixed-width types (probably because these types aren't really part of the language itself). From what i gathered from [Stackoverflow](https://stackoverflow.com/questions/9225567/how-to-print-a-int64-t-type-in-c), you can either use some string literal macros (e.g. ```PRId64```, see also [here](http://www.cplusplus.com/reference/cinttypes/) or cast to ```intmax_t``` / ```uintmax_t``` and use the ```j``` modifier. Out of the two, the latter approach seemed less ugly.

> and I see no point not to just use a 64bit type (e.g. %llu and uint64).

I don't think that ```%llu``` = ```uint64_t``` holds universally. I it is probably true for every current architecture, but I don't think it is portable. So unless there's something in that regard in the standard, I think the current approach is as good as it gets.

**Comment by AlexanderKurtz** [comment]
I just added the commit from #71 to this PR and also another fix because clang treats using ```%p``` together with a ```char*``` as an error. This should be ready to merge now!

**Comment by AlexanderKurtz** [comment]
We really should merge #62, this PR just failed Travis twice (but only on one of six tests) because of some network failure when downloading g++. This is really frustrating :-(

**Comment by weidendo** [comment]
> I don't think that %llu = uint64_t holds universally.

Doesn't need to.
Just cast a uint64_t type we want to print explicitly to "unsigned long long" in the printf() call.
This will always work. No need to use obscure printf functionality.

We already had a similar problem for making the code portable between Linux and MacOS:
they use a different typedef for uint64_t. We either get a warning on Linux or on MacOS without
a cast.

**Comment by AlexanderKurtz** [comment]
Ok, just so I get this right: You simply prefer ```%llu``` and ```(unsigned long long)``` to ```%ju``` and ```(uintmax_t)```. Right?

**Comment by weidendo** [comment]
Yes, as done in laik_log_Space() in debug.c (ah, that needs to be fixed to "%lld" and "long long"...).

**Comment by AlexanderKurtz** [comment]
Alright, I just pushed a new version implementing this!

**Pull request merged**
