### PR TITLE
README.md: Add a list of all packages which should be installed on De…

### PR DESCRIPTION
**Pull request by AlexanderKurtz**
…bian/Ubuntu when building LAIK.

This list was compiled after trying to build LAIK in a minimal Debian
stretch VM, so it should be quite complete.

### CODE REVIEW

**Comment by weidendo** [comment]
Good!

Not all dependencies are equal:

We should specify optional packages, which then get detected by ./configure,
and set define flags in Makefile.config and/or subdirectories to compile in Makefile.

* gcc - Yes
* g++ - not needed. LAIK is C. In the future, this could be become optional for a nice C++ API.
* libmosquitto-dev: optional for MQTT agents
* libopenmpi-dev: optional for MPI backend/driver
* libpapi-dev: optional for more detailed profiling information.
* libprotobuf-c-dev: optional for any external agents using protoful
*￼ make: Yes
* openmpi-bin: optional for MPI backend/driver
* openssh-client: No. Or needed by TCP backend? If yes, optional
* protobuf-c-compiler: optional for any external agents using protoful
* python: Yes, for configure and probably in the future unit-test driver 
* uuid-dev: optional for agents using (@Dai: why?)

**Comment by AlexanderKurtz** [comment]
I agree, that not all dependencies are strictly necessary. However ```g++``` is actually needed for the raytracer example and ```ssh``` is actually needed since mpirun will complain if it's missing (even though it doesn't use it):

```
$ mpirun id
--------------------------------------------------------------------------
The value of the MCA parameter "plm_rsh_agent" was set to a path
that could not be found:

  plm_rsh_agent: ssh : rsh

Please either unset the parameter, or check that the path is correct
--------------------------------------------------------------------------
$ 
```

**Comment by AlexanderKurtz** [comment]
Regarding ```uuid-dev```: I don't currently see where that's used at all. ```configure``` checks for it and ```external/MQTT/Makefile``` mentions it in a comment, but I don't think any code actually uses it (not even ifdef-ed.

**Comment by twittidai** [comment]
Hi, 

It is not used currently and will be removed after the “redesign”

**Comment by AlexanderKurtz** [comment]
I just pushed a new version, please review!

**Comment by weidendo** [comment]
SSH is not directly required by LAIK, thus it is not a dependency.
If installing openmpi in Debian does not draw in ssh, then the package dependencies are
wrong in Debian. But this has nothing to do with LAIK.

**Comment by AlexanderKurtz** [comment]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=882603

**Pull request merged**
