### PR TITLE
configure: Fix broken check for OMP.

### LINKED ISSUE #30: configure check for OMP is incorrect
The ```configure``` script checks for OMP like this:

```
omp_enabled = False
mycc = cc;
if not cc:
    mycc = "cc"
ccout = subprocess.check_output([mycc, '--version'])
if ccout[:3] == "gcc":
    omp_enabled = True
if omp_enabled:
    print("Enabling OpenMP in examples");
```

However

```
alexander@shepard:~$ readlink --canonicalize /usr/bin/cc
/usr/bin/x86_64-linux-gnu-gcc-7
alexander@shepard:~$ /usr/bin/cc --version
cc (Debian 7.2.0-16) 7.2.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

alexander@shepard:~$ 
```

So, ```gcc``` will identify itself as ``cc`` if it is called as ```cc```, which makes sense. A better check would be to run ```cc --version -fopenmp``` and check the exit code.

### PR DESCRIPTION
**Pull request by AlexanderKurtz**
Closes #30.

### CODE REVIEW

**Comment by twittidai** [comment]
I would prefer if omp for clang is also properly set instead of disabling omp on non-gcc compiler. 
this also need to work for icc since may user may compile their code using icc.

**Comment by AlexanderKurtz** [comment]
Regarding the Travis failure, I'm looking into this. Regarding clang, what exactly is the problem here? On my system:

```
alexander@shepard:~/git/laik$ clang --version -fopenmp
clang version 3.8.1-24 (tags/RELEASE_381/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
alexander@shepard:~/git/laik$ echo $?
0
alexander@shepard:~/git/laik$ 
```

According to <https://openmp.llvm.org/> this requires clang 3.8.

**Comment by AlexanderKurtz** [comment]
Ok, so regarding Travis: It seems Travis ships clang 3.9 (which is > 3.8) so OpenMP support should work. However, they then don't install the LLVM version of libomp¹, because that's only available since Ubuntu Xenial. Consequently, our dynamically linked test executables fail to start.

[1] https://packages.ubuntu.com/xenial/libomp5

NB: We are not the only ones falling into this trap:
https://github.com/travis-ci/travis-ci/issues/8315#issuecomment-328672030
https://github.com/boutproject/BOUT-dev/issues/492
https://github.com/UCL/STIR/issues/117

However, I do have an idea on how to fix this...

**Comment by twittidai** [comment]
I rechecked macOS behaviour. It works now. 
How ever, icc does not which is still a issue.

**Comment by AlexanderKurtz** [comment]
Am I correct to assume that ICC requires ```-openmp``` instead of ```-fopenmp```¹?

[1] https://stackoverflow.com/questions/6482845/icc-on-linux-link-to-openmp

**Comment by twittidai** [comment]
See:  https://software.intel.com/en-us/node/522690

**Comment by AlexanderKurtz** [comment]
Sigh. So OMP requires *both* a compiler flag and a dynamic library. And those obviously differ between gcc, clang, and icc. This is why we can't have nice things :-(

**Comment by AlexanderKurtz** [comment]
During testing, I encountered an additional failure if OpenMP was supported, but disabled (i.e. the ```-fopenmp``` flag was not passed), so I just opened #32. @twittidai Please review!

**Comment by AlexanderKurtz** [comment]
Aha! Ubuntu Trusty may not ship LLVM's version of libomp, but it does ship Intel's version:

https://packages.ubuntu.com/trusty/libiomp-dev

**Comment by AlexanderKurtz** [comment]
And it turns out, that libiomp and libomp are really the same thing: 
https://packages.debian.org/sid/libiomp-dev
They do use different SONAMEs though...

**Comment by AlexanderKurtz** [comment]
Ok, so this turns out to be *hard*: Intel's ICC doesn't support ```-fopenmp``` and we can't risk calling the other compilers with ```-openmp``` even for checking for support for this option, because they may interpret that as "put the output in ```penmp```. Sigh. Honestly, this is yet another example of why invoking compilers is something which should really not be done by humans.

Anyway, after some time on the interwebs, I found something which the official documentation¹ neglects to mention (at least for Linux): ICC deprecated ```-openmp``` in favor of ```-qopenmp```² (naturally, using ```-fopenmp``` like everybody else didn't seem to be an option...).

/rant off

So, all in all the latest version of this PR should deal with all the "peculiarities" in Travis *and* ICC. @twittidai could you test this with ICC?

[1] https://software.intel.com/en-us/node/522690
[2] https://stackoverflow.com/questions/40107986/icpc-command-line-error-option-openmp-not-supported

**Comment by weidendo** [comment]
As we claim that LAIK can co-exist with OpenMP, we should have a test in Travis with LAIK usage and OpenMP enabled. This must be covered by the configure check for OpenMP, ie  that it finds and enables OpenMP in Travis.

But I do not think that the configure check has to be perfect for all compilers (what about PGI or MIPSpro). There always is the option to manually change the configuration in Makefile.config after a configure run, also useful to disable/enable features.

**Comment by AlexanderKurtz** [comment]
Shouldn't ```examples/spmv2.c``` do that already (with this PR, because before OpenMP was basically always disabled because of #30).

**Comment by weidendo** [comment]
Now I am confused. Do PRs trigger a Travis run? Where can I see the result?
I am fine with merging #30 and this, if it does the right thing in Travis, ie. enabling OpenMP for spmv2 with both gcc and clang...

**Comment by weidendo** [comment]
Forget my last comment, I just saw the green checkmark, and the Travis logs for gcc / clang both enable OpenMP.

Hmm. Is there a way to run the Intel compiler in Travis??

**Comment by AlexanderKurtz** [comment]
PRs do trigger Travis, the results are linked at the bottom of the PR ("Show all checks"). This PR does the right thing for both gcc and clang. But I had to install an additional library (see changes in ```.travis.yml```), and so will people who use LAIK with clang. That's the problem that #34 was trying to solve.

**Comment by AlexanderKurtz** [comment]
> Hmm. Is there a way to run the Intel compiler in Travis??

Is there a way to *legal* and *scriptable* way to get the Intel compiler?

**Comment by twittidai** [comment]
Intel compiler requires a license which is I think not available under travis.

**Pull request merged**
