### PR TITLE
src/backends/tcp/backend.c: Stop pretending that we support anything but the synchronous API.

### PR DESCRIPTION
**Pull request by AlexanderKurtz**

### CODE REVIEW

**Comment by weidendo** [comment]
Curious: I want to understand how tricky it is to enable the new functionality of the MPI backend for
the TCP backend, given that it is mostly only implementing the MPI functions.
Is copying src/backend-mpi.c over src/backends/tcp/backend.c and try to make it compile again easy?

**Comment by AlexanderKurtz** [comment]
I just tried this and the main problem is that ```backend-mpi.c``` accesses ```MPI_COMM_WORLD``` before it calls ```MPI_Init()```. I tried to consult the [relevant section of the standard](http://mpi-forum.org/docs/mpi-3.1/mpi31-report/node28.htm#Node28) regarding this, but didn't find anything conclusive. Is this legal or not?

**Comment by AlexanderKurtz** [comment]
The background is that my ```MPI_COMM_WORLD``` is a external pointer variable which is ```NULL``` before ```MPI_Init()``` and dynamically allocated afterwards. If this change in value is forbidden by the MPI standard, I can of course use a static memory location instead, but I want get your opinion on this first!

**Comment by weidendo** [comment]
MPI_COMM_WORLD makes no sense without MPI_Init. This is a bug and needs to be fixed.
Where is this done?

**Comment by AlexanderKurtz** [comment]
```MPI_COMM_WORLD``` is accessed in [line 83](https://github.com/envelope-project/laik/blob/master/src/backend-mpi.c#L83) and [line 90](https://github.com/envelope-project/laik/blob/master/src/backend-mpi.c#L90) ```MPI_init()``` is called in [line 94](https://github.com/envelope-project/laik/blob/master/src/backend-mpi.c#L94).

**Comment by weidendo** [comment]
Ok, just fixed in e6b5d36.

**Comment by AlexanderKurtz** [comment]
> Ok, just fixed in e6b5d36.

Thanks!

> Curious: I want to understand how tricky it is to enable the new functionality of the MPI backend for
the TCP backend, given that it is mostly only implementing the MPI functions.
Is copying src/backend-mpi.c over src/backends/tcp/backend.c and try to make it compile again easy?

I am a little surprised myself, but yes, it is really easy! I just did this on top of the latest git master:

```
$ cp src/backend-mpi.c src/backends/tcp/backend.c 
$ sed -i 's/<mpi.h>/"mpi.h"/' src/backends/tcp/backend.c 
$ sed -i 's/laik_init_mpi/laik_init_tcp/' src/backends/tcp/backend.c 
$ sed -i 's/__attribute__ ((warn_unused_result))//' src/backends/tcp/minimpi.h
$ 
```

And everything still compiles and the tests also work!

**Comment by AlexanderKurtz** [comment]
Oh, and the other way around also works! This is all that's necessary to use the TCP backend's backend.c with OpenMPI:

```Diff
diff --git a/src/backends/tcp/backend.c b/src/backends/tcp/backend.c
index baa8880..3e70fbc 100644
--- a/src/backends/tcp/backend.c
+++ b/src/backends/tcp/backend.c
@@ -7,7 +7,7 @@
 #include <string.h>         // for memcpy
 #include "debug.h"          // for laik_tcp_always
 #include "errors.h"         // for laik_tcp_errors_push, laik_tcp_errors_pre...
-#include "mpi.h"            // for MPI_Comm, MPI_Datatype, MPI_COMM_WORLD
+#include "/usr/lib/x86_64-linux-gnu/openmpi/include/mpi.h"            // for MPI_Comm, MPI_Datatype, MPI_COMM_WORLD
 
 /* Internal functions */
 
diff --git a/tests/tcp/common.sh b/tests/tcp/common.sh
index 7f63917..ec8ade3 100755
--- a/tests/tcp/common.sh
+++ b/tests/tcp/common.sh
@@ -2,14 +2,7 @@
 
 run()(
     IFS='_'
-    idx="0"
-
-    while [ "${idx}" -lt "${OMPI_COMM_WORLD_SIZE}" ]; do
-        ../../examples/${1} &
-        idx="$((idx + 1))"
-    done
-
-    wait
+    mpiexec -n 4 ../../examples/${1}
 )
 
 dir="`dirname -- "${0}"`"
```

**Comment by weidendo** [comment]
Good to know!

There still will be quite some cleanup in the MPI backend, and I want to move most code out of it.
Almost the only thing remaining should be the execution of the action sequence.

I want to do 2 versions of the function executing the actions: one synchronous, the other
asynchronous. However, it should be enough to just remove the 2nd version to still make
it work with the TCP backend.

Again just wondering: what would be needed for an asynchronous TCP backend? Just a 2nd thread
running the action sequence synchronously, ie. we just can use your current code?
This 2nd thread would mostly wait in select(), so for communication among threads, it probably would
be better to also use a file descriptor. It looks to me that this can be implemented in a quite clean
way, even for making the current MPI backend asnychronous without really using MPI_ISend/IRecv.

**Pull request merged**
