### PR TITLE
.travis.yml: Cleaned up and rewritten to use Docker.

### PR DESCRIPTION
**Pull request by AlexanderKurtz**

### CODE REVIEW

**Comment by AlexanderKurtz** [comment]
Hey @weidendo! I took your suggestion from #47 and created a Dockerfile for LAIK and made Travis use it. Here's the TL;DR of this PR compared to the current situation:

 1. Faster Travis runs (compare e.g. https://travis-ci.org/envelope-project/laik/builds/328343489 to https://travis-ci.org/envelope-project/laik/builds/328510259)
 2. More reliable Travis runs (see e.g. https://travis-ci.org/envelope-project/laik/builds/316965321 which failed just because some PPA failed to download).
 3. Less code (+49/-92 lines).
 4. No third-party repositories, PPAs, etc.
 5. Multi-distro testing (currently Debian Stretch and Ubuntu Xenial, new versions should also work)
 6. Defined environment in contrast to the Frankenstein-like Ubuntu Trusty provided by Travis (see e.g. https://travis-ci.org/envelope-project/laik/jobs/326726918#L543)
 7. Last but not least: You can now simply run ```docker build .``` inside the source tree to test your changes!

What do you think?

**Comment by AlexanderKurtz** [comment]
Just for reference why point 2 is important: I just had to force-push three identical (except for the dates) versions of the commit in #67 because Travis failed the first two times with some download error:

1. https://travis-ci.org/envelope-project/laik/builds/329964753 (FAIL)
2. https://travis-ci.org/envelope-project/laik/builds/329968178 (FAIL)
3. https://travis-ci.org/envelope-project/laik/builds/329969991 (PASS)

This is really frustrating. I absolutely think that only CI-passings PRs should be merged (or even be posted), but Travis' network hickups make this really difficult. :-(

**Comment by weidendo** [comment]
Indeed, but do you think a docker image will improve the situation? Either Travis errors on building the image, or the built image may not be accessable. Or where is the image stored?

**Comment by AlexanderKurtz** [comment]
Well, I have done a few pushes with Docker now (mainly this PR and #64), and none of them failed because of such a network error. So yes, I think using a Docker image does improve the situation (drastically). Also, I'm pretty sure that Travis has local cache for Docker images, because when watching the build in real-time, the initial "stretch: Pulling from library/debian" step takes almost no time. So, the only network services which could potentially fail seem to be deb.debian.org and archive.ubuntu.com, and those seem to be quite reliable.

**Comment by AlexanderKurtz** [comment]
As discussed during the meeting, I have just pushed a new version of this PR which added a test run with GCC 4.x (Ubuntu Xenial's gcc/g++ 4.7 to be exact). I think this PR is ready now and Travis seems to like it too, so can we merge this now?

**Comment by weidendo** [comment]
I just tried to understand the output of the new Travis runs..
    https://travis-ci.org/envelope-project/laik/jobs/334771232
It starts with a lot of (around line 415) failures about connecting to PPAs. No idea why it then
has no problem fetching the large amount of packages afterwards. Are you sure this really
improves the current state?

I see it also removes the "clang-tidy check"...
But let's see, we always can go back :-)

**Comment by AlexanderKurtz** [comment]
Thanks! Regarding the PPA failures: That's a Travis implementation detail. As can be seen [here](https://travis-ci.org/envelope-project/laik/jobs/326726918#L543) Travis installs **a lot of** package sources per default, some of them apparently seem to fail randomly. This is not our fault and I don't think there's anything we can do about it.

**Comment by AlexanderKurtz** [comment]
Regarding clang-tidy: I just opened #72 about this. I would assign myself, but GitHub doesn't let me do that (you probably have to be a member for this). Anyway, I will have a try at this!

**Comment by weidendo** [comment]
Rechecking the Travis output: What I really dislike about this is that neither the compile steps nor running the tests is now shown in the Travis console.

If there is a compile error with one of the configured compilers, or a test fails, how do I see the compile error, or which test actually failed? Everthing is hidden behind the docker run command.

How to make the output of "make && make test" visible again in the Travis console? I am tempted to revert this PR.

**Comment by weidendo** [comment]
Ah, forget it. I was confused by the overwhelming amount of useless output like "Unexpected end of /proc/mounts line `overlay / overlay ..."

**Comment by AlexanderKurtz** [comment]
> Ah, forget it. I was confused by the overwhelming amount of useless output like "Unexpected end of /proc/mounts line `overlay / overlay ..."

Yeah, that line sucks. However, I noticed that it only happens on the Ubuntu test runs, the Debian runs are fine...

**Comment by AlexanderKurtz** [comment]
> https://stackoverflow.com/questions/46138549/docker-openmpi-and-unexpected-end-of-proc-mounts-line

So, it seems this is actually a bug in OpenMPI...

**Comment by AlexanderKurtz** [comment]
Yup, it's an OpenMPI bug, open-mpi/ompi#1822 to be exact. This also explains the Debian vs. Ubuntu difference: Debian Stretch has OpenMPI 2.0.2 [0], while Ubuntu Xenial only has 1.10.2 [1].

[0] https://packages.debian.org/source/stretch/openmpi
[1] https://packages.ubuntu.com/source/xenial/openmpi

**Pull request merged**
