### PR TITLE
Add CMake as an alternative build system.

### LINKED ISSUE #50: Support out-of-tree builds
Running configure from a separate build directory does not lead to usable Makefiles in the build directory; and running `ln -s $SRCDIR/Makefile $BUILDDIR/Makefile` is not sufficient either.

### PR DESCRIPTION
**Pull request by AlexanderKurtz**
Closes #50.

### CODE REVIEW

**Comment by twittidai** [comment]
Please merge this.
It seems to be full compatible with makefile solution. 
I would like to see this to proceed further integration with both TCP backend and lauSim (which is also using CMake).

**Comment by AlexanderKurtz** [comment]
Ok, I will make the CMake PR one big PR which doesn't touch the existing build and test system.

**Comment by AlexanderKurtz** [comment]
@twittidai: As discussed yesterday, I just pushed a new version of this PR which doesn't modify the existing ```Makefiles``` or ```*.expected``` files.

The PR does however modify the ```Dockerfile``` to use CMake for building. I think this is necessary since we probably want **all** backends to be tested on Travis runs and the ```Makefile``` only tests the MPI backend (not even the ```single``` backend). Is this ok?

**Comment by twittidai** [comment]
I think all backends shall be tested. In addition, cmake seems not to interfere with the current makefile system. 
Merged.

**Pull request merged**
