### PR TITLE
src/core.c: Allow selecting the backend dynamically via the LAIK_BACK…

### PR DESCRIPTION
**Pull request by AlexanderKurtz**
…END environment variable.

### CODE REVIEW

**Comment by AlexanderKurtz** [comment]
@twittidai: I rewrote this so that it can be merged ahead of the main CMake PR, could you have a look and merge if possible?

**Review by twittidai — APPROVED** [review]
Seems ok.

**Comment by AlexanderKurtz** [comment]
I just noticed that the error reporting in case of a missing backend doesn't work as intended:

```
$ LAIK_BACKEND=foo examples/vsum
vsum: ../src/core.c:447: log_flush: Assertion `laik_loginst != 0' failed.
Aborted
$ 
```

It seems that the following line is the problem:

```
laik_log (LAIK_LL_Panic, "LAIK was compiled without the %s backend requested by LAIK_BACKEND", override);
```

@weidendo: Am I correct to assume that ```laik_log()``` only works after ```laik_new_instance()``` has been called? If so, is there another function for the "please just print an error message and exit" problem (aside from ```fprintf (stderr)``` and ```exit```)?

**Comment by AlexanderKurtz** [comment]
Hi @weidendo! I just saw that you pushed 95bd4466829cd549fdc4f6879323a98c7dfce9ea to fix the error reporting. However, while your solution (create a dummy "single" backend) works there, I still need a way to report errors before ```laik_new_instance()``` has been called. Does such a way exist in LAIK?

**Pull request merged**
