### PR TITLE
Also add "src" to the include path in all sub Makefiles.

### PR DESCRIPTION
**Pull request by AlexanderKurtz**
Unfortunately I missed these in #102, sorry about that!

### CODE REVIEW

**Comment by weidendo** [comment]
Headers in "src/" never are part of the public API. So this definitly should not be added to anything in "examples/".

@twittidai: what is the idea of the "external/" subdirectory? If this is about plugins, I also would argue that these should compile without headers in "src".

**Comment by AlexanderKurtz** [comment]
> Headers in "src/" never are part of the public API. So this definitly should not be added to anything in "examples/".

I think our [include guidelines](https://github.com/envelope-project/laik/blob/master/Guidelines.md#header-files-and-include-directives) are quite clear in this point:

> 2. When building LAIK (as in the project), both include and src MUST be in the include path.

The part which prevents the examples from accessing private interfaces is

> 3. The examples MUST only include headers from include.

This was intentionally separated because of issues like #111. This essentially comes down to the question of whether ```laik-internal.h``` should be considered (public) API or not. What's the answer here?

**Comment by weidendo** [comment]
We have 2 types of public APIs: for LAIK users, and for LAIK plugin developers. We even may have examples for both. But headers in "src/" definitely are internal, and examples are for users to understand our public APIs.

If our guidelines currently does not reflect that, the guidelines is wrong.

**Comment by AlexanderKurtz** [comment]
> If our guidelines currently does not reflect that, the guidelines is wrong.

Ok, I just filed #113 about this!

**Pull request closed without merging**
