### PR TITLE
tests: Run the examples using a new wrapper script.

### PR DESCRIPTION
**Pull request by AlexanderKurtz**
Compared to the current situation, this brings the following advantages:

 1. We also capture stderr, which makes debugging test failures easier.
 2. We always enable logging via LAIK_LOG which also eases debugging.
 3. For the MPI tests, every line in the output is prefixed by a process
    identifier.
 4. We only sort the output by this identifier, leaving the output order
    of a single process intact.
 5. We sort using a defined locale which avoids bugs like these
    (this was for example encountered during the development of #62):

    ```
    $ printf ' 1a\n11a\n' | LC_ALL=en_US.UTF8 sort
    11a
     1a
    $ printf ' 1a\n11a\n' | LC_ALL=C sort
     1a
    11a
    $
    ```

### CODE REVIEW

**Comment by weidendo** [comment]
In general: yes, we really should go to a better test infrastructure. However, instead of starting with a bash script which soon will need to be expanded, why not go with a python script... Would the proposed shell script be enough for envisioned unit tests?

Regarding to your specific points:

Capturing stderr is a good thing.

But setting LAIK_LOG really should be done per test case. It easily can produce GBs of output, slowing down the test suite.

Regarding the MPI output tagging: I did not know about "--tag-output". I am just wondering... is this option specific to OpenMPI? LAIK log output already has a prefix which allows deterministic sort results. At the moment, all tests which write something to stdout only do that from master. If we keep it this way, we do not need the tagging. And if there really is a need for testing output from different tasks, we always can use laik_log for that.

Regarding locale specific sorting: good catch!

**Comment by AlexanderKurtz** [comment]
Hi!

Some context first: The problem with the current approach to testing is that it's not how meson, CMake, or any other build framework expect tests to work: They expect tests to essentially be a (single) command (optionally with arguments, but not a shell command line) which when executed returns either 0 (Success) or !0 (Failure). Our tests currently consists of running the examples, catching their stdout, post-processing it, and then comparing it to a known (good) value. This script essentially translates one onto the other. If we want to use *any* modern build system, we most certainly need such a script. If it's Python, Shell, or a C program really doesn't matter, what matter's is the call semantics.

> In general: yes, we really should go to a better test infrastructure. However, instead of starting with a bash script which soon will need to be expanded, why not go with a python script...

I can of course rewrite this in Python, but I don't really see the point, it will probably be a lot longer and harder to maintain. The script essentially has to execute a few external commands with very limited control flow requirements, that's where Shell scripts shine and everything else, well, doesn't.

> Would the proposed shell script be enough for envisioned unit tests?

This script has nothing to do with unit tests. If we add unit tests, they'd probably be very small C programs, linked against liblaik, which essentially have a main() method full of asserts. This script is just for making the currently existing black-box tests available to CMake in a convenient way.

> Regarding to your specific points:
> Capturing stderr is a good thing.
> But setting LAIK_LOG really should be done per test case. It easily can produce GBs of output, slowing down the test suite.

I just tried disabling LAIK_LOG in my CMake build and got more or less the same build times as before, so I don't think this is a problem as of today. And honestly, I'd consider it a bug if the debug output was in the order of gigabytes, since it'd essentially be impossible to view the debug log in an editor, let alone read it.

> Regarding the MPI output tagging: I did not know about "--tag-output". I am just wondering... is this option specific to OpenMPI?

mpirun itself is specific to OpenMPI, e.g. MPICH uses [mpiexec](https://www.mpich.org/static/docs/v3.2/www1/mpiexec.html). Is there anything about wrapper tools in the MPI standard?

> LAIK log output already has a prefix which allows deterministic sort results. At the moment, all tests which write something to stdout only do that from master. If we keep it this way, we do not need the tagging. And if there really is a need for testing output from different tasks, we always can use laik_log for that.

Yes, we do need the tagging since e.g. examples/vsum writes on all processes.

> Regarding locale specific sorting: good catch!

Yeah, honestly I felt like punching a wall when I tracked this one down... :-(

So, all in all, please consider merge this, it makes test failures a lot easier to debug and is necessary for using CMake (#64)!

**Comment by weidendo** [comment]
> The problem with the current approach to testing is that it's not how meson, CMake, or any other build framework expect tests to work...

You run a test case now with "make testcase", which returns 0 or !0. Exactly what CMake expects.
What is the problem?

This PR is "improving" stuff in 5 ways. Can we separate the issues? This would reduce the discussion and make the PRs much easier to merge.

> This script essentially translates one onto the other.

But enforcing common policies over all tests such as the LAIK_LOG setting...

**Comment by AlexanderKurtz** [comment]
> You run a test case now with "make testcase", which returns 0 or !0. Exactly what CMake expects.
What is the problem?

I am sorry, but I don't get this point: Should CMake call make to run the tests? Doesn't that defeat the purpose of having CMake in the first place?

> This PR is "improving" stuff in 5 ways. Can we separate the issues? This would reduce the discussion and make the PRs much easier to merge.

I am all for small PRs, in fact this PR *is* an attempt to make the CMake PR (#64) smaller. But unfortunately I don't see how this PR can be split up even further. Do you have any particular aspects you would like to have split out? Or would you prefer if I just put this in the CMake PR and leave the Make test infrastructure as it is? This is of course possible, but then we'd essentially have two sets of test cases...

> But enforcing common policies over all tests such as the LAIK_LOG setting...

Yes, because I fundamentally believe that getting as much debug info as possible when running the test suite is a good idea. However, if you have strong opinions about this one, I can of course remove this bit.

**Comment by weidendo** [comment]
> Yes, we do need the tagging since e.g. examples/vsum writes on all processes.

Ah, yes. That was exactly why I did the sorting here in the first place.
But what was the point of labelling? We only need to normalise the output for comparing to an expected result. Sorting is enough for that.

I just checked: MPICH 1 used mpirun, too. But the standard suggests mpiexec nowadays, as used by current MPICH. And OpenMPI also has mpiexec as alias to mpirun/orterun. So we can use mpiexec in the tests for both OpenMPI and MPICH. But for labelling the output, OpenMPI uses a different flag than MPICH.

**Comment by AlexanderKurtz** [comment]
> But what was the point of labelling? We only need to normalise the output for comparing to an expected result. Sorting is enough for that.

Well, I obviously have to debug test failures **a lot**, and this becomes a lot easier if stdout is not rearranged seemingly randomly and always has a prefix indicating which process actually printed the line. And no, ```laik_log()``` and ```printf ("%d\n", myid)``` isn't working here for me, since they rely on a correctly working backend code, so they won't work if for example my ```laik_init()``` or ```updateGroup()``` implementation is broken.

**Comment by twittidai** [comment]
Discussion today: 
this will be merged if both testing facilities (cmake and makefile-as-now) will run.
Cmake must be full independent from current build and test system.

**Pull request closed without merging**
